java_thrift_library(
  name='java',
  sources=rglobs('*.thrift'),
  dependencies=[
    '3rdparty/jvm:thrift',
  ]
)

python_thrift_library(
  name='python',
  sources=rglobs('*.thrift'),
  dependencies=[
    '3rdparty/python:thrift',
  ]
)
