<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>acid</string>
	</array>
	<key>keyEquivalent</key>
	<string>^@C</string>
	<key>name</key>
	<string>Caustic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.caustic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*((//).*$\n?)</string>
			<key>name</key>
			<string>comment.line.caustic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(def|del|elif|else|extends|if|import|module|record|return|rollback|service|while|var)\b</string>
			<key>name</key>
			<string>keyword.control.caustic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==?|!=|&amp;lt;=|&amp;gt;=|&amp;lt;&amp;gt;|&amp;lt;|&amp;gt;</string>
			<key>name</key>
			<string>keyword.operator.comparison.caustic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\-|\+|\*|/(?![/*])|%</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.caustic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|&amp;amp;&amp;amp;|\|\|</string>
			<key>name</key>
			<string>keyword.operator.logical.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|null|true)\b</string>
			<key>name</key>
			<string>constant.language.caustic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
			<key>name</key>
			<string>constant.numeric.scala</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.caustic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(?:[btnfr\\"']|[0-7]{1,3}|u[0-9A-Fa-f]{4})</string>
					<key>name</key>
					<string>constant.character.escape.caustic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Unit|Boolean|Int|Double|String)\b</string>
			<key>name</key>
			<string>storage.type.primitive.caustic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.caustic</string>
	<key>uuid</key>
	<string>6C83F0BC-0075-4AE2-97C1-D74E389ECF3A</string>
</dict>
</plist>
