python_library(
  name='python',
  sources=rglobs('*.py'),
  provides=setup_py(
    name='caustic.pants',
    version='1.0.7',
    description='Caustic plugin for Pants',
    url='https://github.com/ashwin153/caustic',
    author='Ashwin Madavan',
    author_email='ashwin.madavan@gmail.com',
    license='Apache License, Version 2.0',
    zip_safe=True,
    classifiers=[
      'Intended Audience :: Developers',
      'License :: OSI Approved :: Apache Software License',
      'Operating System :: OS Independent',
      'Programming Language :: Python',
    ]
  )
)
