scala_library(
  name = 'scala',
  sources = rglobs('*.scala'),
  dependencies = [
    '3rdparty/jvm:akka',
  ],
  provides = artifact(
    org = 'com.madavan',
    name = 'schema-runtime_2.12',
    repo = public,
    publication_metadata = describe,
  ),
)
